name: Laravel CI

on:
  push:
    branches: [main]
    paths: "app/backend/**"
  pull_request:
    branches: [main]
    paths: "app/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret123
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U laravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: sqlite, mbstring, bcmath

      - name: Install Composer dependencies
        working-directory: app/backend
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        working-directory: app/backend
        run: cp .env.example .env

      - name: Set SQLite config
        working-directory: app/backend
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i '/DB_HOST/d' .env
          sed -i '/DB_PORT/d' .env
          sed -i '/DB_DATABASE/d' .env
          sed -i '/DB_USERNAME/d' .env
          sed -i '/DB_PASSWORD/d' .env
          touch database/database.sqlite

      - name: Generate app key
        working-directory: app/backend
        run: php artisan key:generate

      - name: Run database migrations
        working-directory: app/backend
        run: php artisan migrate:fresh --seed --force
