name: Laravel CI

on:
  push:
    branches: [main]
    paths: "app/backend/**"
  pull_request:
    branches: [main]
    paths: "app/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret123
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U laravel"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: laravel_test
      DB_USERNAME: laravel
      DB_PASSWORD: secret123

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo_pgsql, mbstring, bcmath
          coverage: none

      - name: Install Composer dependencies
        working-directory: app/backend
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        working-directory: app/backend
        run: cp .env.example .env

      - name: Generate app key
        working-directory: app/backend
        run: php artisan key:generate

      - name: Run database migrations
        working-directory: app/backend
        run: php artisan migrate:fresh --seed --force
